<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HBRB43M" failures="2" tests="5" name="Test" time="21.278" errors="0" timestamp="2023-08-04T17:45:37 IST">
  <testcase classname="mytestpackage.test.ValidationErrorTest" name="checkLogin" time="0.188"/>
  <testcase classname="mytestpackage.test.ValidationErrorTest" name="errorMessage" time="0.359"/>
  <testcase classname="mytestpackage.test.StandAlone" name="submitOrder" time="4.352">
    <failure type="java.lang.AssertionError" message="expected [THANKYOU FOR THE ORDER.] but found [THANK FOR THE ORDER.]">
      <![CDATA[java.lang.AssertionError: expected [THANKYOU FOR THE ORDER.] but found [THANK FOR THE ORDER.]
at mytestpackage.test.StandAlone.submitOrder(StandAlone.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="mytestpackage.test.StandAlone" name="submitOrder" time="4.303">
    <failure type="java.lang.AssertionError" message="expected [THANKYOU FOR THE ORDER.] but found [THANK FOR THE ORDER.]">
      <![CDATA[java.lang.AssertionError: expected [THANKYOU FOR THE ORDER.] but found [THANK FOR THE ORDER.]
at mytestpackage.test.StandAlone.submitOrder(StandAlone.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="mytestpackage.test.StandAlone" name="verifyProduct" time="0.0">
    <skipped/>
  </testcase> <!-- verifyProduct -->
</testsuite> <!-- Test -->
